name: Update ArXiv Papers

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every midnight

jobs:
  update-papers:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Fetch latest papers
        run: node src/scripts/fetch-papers.js

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/index.html
          git commit -m "Update papers from arXiv"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}